### ISSUE TITLE
Setup Tutorial

### ISSUE THREAD

**Issue by jepunband** [grcasanova/RougeCaptivePortal#1]
Hi, can you please do a setup tutorial on how to install and setup ESP8266 with your captive portal.

Thank you.

**Comment by OxMarco** [comment]
Hi, you simply need to upload the code to the ESP and then wait for incoming connections

**Comment by towsiksys** [comment]
Hi can u please describe more information how to edit config.h and other things on Esportal.ino

**Comment by OxMarco** [comment]
Now it should be clearer, updated description and comments in files

**Comment by mishalshanavas** [comment]
how do i acess the admin page
