### ISSUE TITLE
Login portal pops up is not showing

### ISSUE THREAD

**Issue by shahriarshafin** [grcasanova/RougeCaptivePortal#2]
First of all, thank you so much for the project.I've been looking for a long time. Everything is ok with me but The LOGIN PORTAL pops up is not showing. If I manually go to the index with address then it's working. What can I do now...

**Comment by OxMarco** [comment]
Thank you for your comments. Regarding the issue, it's probably due to a change in the base root for captive portals. Try tweaking the `PORTALLOGIN_redirect` constant.

**Comment by shahriarshafin** [comment]
thank you
