### ISSUE TITLE
how to acess the admin page

### ISSUE THREAD

**Issue by mishalshanavas** [grcasanova/RougeCaptivePortal#3]
how can i see the saved paswards

**what is the url for the admin page**

**Comment by OxMarco** [comment]
Go to _/logs_

**Comment by mishalshanavas** [comment]
ok thank you

can i ask an **other doubt how to clear the log**

**Comment by grcasanova** [comment]
Just flash the chip again, I didn’t implement a way to clear logs

**Comment by OxMarco** [comment]
Added an url to clear all logs
